# Generated by Django 5.1.2 on 2024-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=70, verbose_name='Room Name')),
                ('bedtypecat', models.IntegerField(choices=[(1, 'Single'), (2, 'Double')], verbose_name='Bed Type')),
                ('nbed', models.IntegerField(verbose_name='No. of Bed')),
                ('Price', models.FloatField()),
                ('rdesc', models.CharField(max_length=500, verbose_name='Description')),
                ('rsize', models.FloatField(verbose_name='Size')),
                ('Address', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
            ],
        ),
    ]
