# Generated by Django 5.1.2 on 2024-11-01 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_alter_rooms_bedtypecat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roombooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Booked'), (3, 'Pending'), (4, 'Canceled')])),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='hotelapp.rooms')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
