# Generated by Django 5.1.2 on 2024-11-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_alter_roombooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='adults',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='child',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='cname',
            field=models.CharField(default=0, max_length=50, verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='mob',
            field=models.IntegerField(default=0, verbose_name='Mobile'),
            preserve_default=False,
        ),
    ]
