# Generated by Django 5.1.2 on 2024-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_roombooking_adults_roombooking_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Booked'), (3, 'Canceled'), (4, 'pending')]),
        ),
    ]
