# Generated by Django 5.1.2 on 2024-11-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_alter_roombooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='mob',
            field=models.BigIntegerField(verbose_name='Mobile'),
        ),
    ]
