# Generated by Django 5.1.2 on 2024-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0007_alter_roombooking_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
