# Generated by Django 5.1.2 on 2024-11-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_alter_roombooking_checkin_alter_roombooking_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomadditionstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimage', models.ImageField(upload_to='image')),
                ('cphoto1', models.ImageField(upload_to='image')),
                ('cphoto2', models.ImageField(upload_to='image')),
                ('swim', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('garden', models.BooleanField(default=False, verbose_name='Garden')),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='hotelapp.rooms')),
            ],
        ),
    ]
