# Generated by Django 5.1.2 on 2024-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_roomadditionstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='cimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='cphoto1',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='cphoto2',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='garden',
            field=models.BooleanField(default=False, verbose_name='Garden'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='swim',
            field=models.BooleanField(default=False, verbose_name='Swimming Pool'),
        ),
        migrations.DeleteModel(
            name='roomadditionstat',
        ),
    ]
